### ISSUE TITLE
Broken with IntelliJ 2020.3

### ISSUE THREAD

**Issue by klassm** [bchatard/alfred-jetbrains#175] opened 2020-12-02 17:06 UTC
**Check [Troubleshooting](/doc/troubleshooting.md) first**

**Describe the bug**
After updating to IntelliJ 2020.3 no projects are shown any more.

**To Reproduce**

1. Update to IntelliJ 2020.3
2. Try to open a project
3. No projects will show up

**Expected behavior**
Projects are shown.

**Additional context**
I did a bit of an investigation. What I found is that paths.js will search recentProjects.xml for the relevant projects. It looks like the file structure has changed quite a bit, the xpath (component[@name='RecentProjectsManager']/option[@name='recentPaths']/list/option/@value) in there does not have any matches.

It now looks like 

```
<application>
    <component name="RecentProjectsManager">
        <option name="additionalInfo">
            <map>
                <entry key="$USER_HOME$/IdeaProjects/.../....-.../some_project">
                    <value>
                        <RecentProjectMetaInfo projectWorkspaceId="1ewcnj5RPnbaLtCQB1MgKesWqVW">
                            <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin"/>
                            <option name="build" value="IU-201.7846.76"/>
                            <option name="buildTimestamp" value="1590980573271"/>
                            <frame x="3072" y="23" width="1280" height="1057"/>
                            <option name="productionCode" value="IU"/>
                            <option name="projectOpenTimestamp" value="1595236712963"/>
                        </RecentProjectMetaInfo>
                    </value>
                </entry>
                <entry>.....</entry>
            </map>
        </option>
    </component>
</application>
```

**Comment by bchatard** [comment] 2020-12-02 17:47
hi @klassm 

thanks for your report and investigations. I will close this issue since the problem is the same in #170 

thanks

**Closed by bchatard** 2020-12-02 17:47 UTC
