### ISSUE TITLE
Can't find any projects on any of installed IDEs

### ISSUE THREAD

**Issue by morgan-kn** [bchatard/alfred-jetbrains#128] opened 2020-04-23 15:20 UTC
I have Rider, CLion, Idea, PyCharm installed. All versions at least 2020.1. 
When I type any of my IDE names in Alfred's Search window, I see an error:

```
Error: Unable to find bin for CLion. Search for bin named: clion
    at getApplicationPath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:115:11)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:155:31)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)
```

JetBrains Toolbox 1.17.6802
Alfred 4.0.9 [1144]

![image](https://user-images.githubusercontent.com/12205621/80116432-a34ffd00-858e-11ea-9511-1ea7bf499ab7.png)

Could you please help me to fix it?

**Comment by bchatard** [comment] 2020-04-24 03:48
duplicate of #126

**Closed by bchatard** 2020-04-24 03:48 UTC

**Comment by morgan-kn** [comment] 2020-04-28 18:22
I still have the same error. Also, I tried to reinstall workflow, and I saw this error in terminal:

`Error: Command failed with exit code 1 (EPERM): alfred-unlink at makeError (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/cleanup.js:7:3 {
  command: 'alfred-unlink',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: "[Error: ENOENT: no such file or directory, open '/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/@bchatard-alfred-jetbrains/info.plist'] {\n" +
    '  errno: -2,\n' +
    "  code: 'ENOENT',\n" +
    "  syscall: 'open',\n" +
    "  path: '/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/@bchatard-alfred-jetbrains/info.plist'\n" +
    '}',
  all: "[Error: ENOENT: no such file or directory, open '/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/@bchatard-alfred-jetbrains/info.plist'] {\n" +
    '  errno: -2,\n' +
    "  code: 'ENOENT',\n" +
    "  syscall: 'open',\n" +
    "  path: '/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/@bchatard-alfred-jetbrains/info.plist'\n" +
    '}',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}`
