### ISSUE TITLE
Unable to install the workflow

### ISSUE THREAD

**Issue by shahdewang** [bchatard/alfred-jetbrains#55] opened 2019-09-01 16:30 UTC
**Describe the bug**
Unable to install. I have used this plugin before, however, was seeing different issues (see https://github.com/bchatard/alfred-jetbrains/issues/48). I started seeing those issues again. I attempted uninstalling and reinstalling and now see the following error.

**To Reproduce**
While installing the npm library, I get the following error -
```
➜  ~ $ npm install -g @bchatard/alfred-jetbrains

> @bchatard/alfred-jetbrains@1.0.12 preuninstall /usr/local/lib/node_modules/@bchatard/alfred-jetbrains
> alfy-cleanup

Error: Command failed: alfred-unlink
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '.'
Require stack:
- /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/.bin/alfred-unlink
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/.bin/alfred-unlink:3:20)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/.bin/alfred-unlink'
  ]
}


    at makeError (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/execa/index.js:174:9)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  code: 1,
  stdout: '',
  stderr: 'internal/modules/cjs/loader.js:775\n' +
    '    throw err;\n' +
    '    ^\n' +
    '\n' +
    "Error: Cannot find module '.'\n" +
    'Require stack:\n' +
    '- /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/.bin/alfred-unlink\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:677:27)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:830:19)\n' +
    '    at require (internal/modules/cjs/helpers.js:68:18)\n' +
    '    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/.bin/alfred-unlink:3:20)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:936:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:790:32)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:703:12)\n' +
    '    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10) {\n' +
    "  code: 'MODULE_NOT_FOUND',\n" +
    '  requireStack: [\n' +
    "    '/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/.bin/alfred-unlink'\n" +
    '  ]\n' +
    '}\n',
  failed: true,
  signal: null,
  cmd: 'alfred-unlink',
  timedOut: false,
  killed: false
}
npm WARN lifecycle @bchatard/alfred-jetbrains@1.0.12~preuninstall: continuing anyway @bchatard/alfred-jetbrains@1.0.12 preuninstall: `alfy-cleanup`
npm WARN lifecycle Exit status 1
npm ERR! code EEXIST
npm ERR! path /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/.bin/rimraf
npm ERR! Refusing to delete /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/.bin/rimraf: is outside /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/rimraf and not a link
npm ERR! File exists: /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/.bin/rimraf
npm ERR! Move it away, and try again.
```

From the debug logs -

```
942 timing stage:runTopLevelLifecycles Completed in 3676ms
943 verbose stack Error: Refusing to delete /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/.bin/xml2js: is outside /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/fast-xml-parser and not a link
943 verbose stack     at clobberFail (/usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:121:12)
943 verbose stack     at isSafeToRm (/usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:114:15)
943 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:54:5
943 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
943 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
943 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:180:7
943 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/node_modules/iferr/index.js:13:50
943 verbose stack     at _readAllLinks (/usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:215:28)
943 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/node_modules/iferr/index.js:13:50
943 verbose stack     at resolveSymlink (/usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:226:22)
943 verbose stack     at _readAllLinks (/usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:217:5)
943 verbose stack     at readAllLinks (/usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:212:3)
943 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:179:5
943 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/node_modules/iferr/index.js:13:50
943 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
943 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/gentle-fs/lib/rm.js:153:16
```

Q | A
--- | ---
Workflow version | _1.0.10_
OSX Version | _10.14.6_
Alfred Version | _4.0.3_
JetBrains Product/Version | 2019.2_
Installation type | JB Toolbox_
Node version | _12.9.1_
NPM version | _6.10.3_

**Comment by bchatard** [comment] 2019-09-02 06:22
duplicate of #22

**Closed by bchatard** 2019-09-02 06:22 UTC
